### ISSUE TITLE
Store passed to both App and Provider

### ISSUE THREAD

**Issue by sbal13** [learn-co-curriculum/map-state-to-props-readme#5]
Store only needs to be passed to Provider in index.js.

**Comment by yehudamakarov** [comment]
yeah seriously. these little things. I went looking at all these tutorials :)

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @sbal13 .

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
