### ISSUE TITLE
TypeError: Cannot read property 'dispatch' of undefined

### ISSUE THREAD

**Issue by Perchitti** [learn-co-curriculum/map-state-to-props-readme#6]
Once I complete the walk-through and click the "Click" button I receive this error...

*Using local server

![screenshot 2018-08-06 14 51 49](https://user-images.githubusercontent.com/31042804/43735515-c5b09b0a-9988-11e8-94f3-62d7908f4627.png)

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Perchitti.

There was a bug in the example code (this.props.store.dispatch should have been this.props.dispatch). We have updated the materials and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by Kang0** [comment]
Hi, this issue was still present during my lab.
