### ISSUE TITLE
labs out of order

### ISSUE THREAD

**Issue by grandballoon** [learn-co-curriculum/map-state-to-props-readme#7]
This lab appears to be out of order. It talks about the app in the last lab not rerendering, when it did. The previous lab also makes use of map state to props, provider, and react-redux, which are only being introduced now.

**Comment by blainelawson** [comment]
Almost a year later, this issue still exists.

**Comment by maxwellbenton** [comment]
Hi @grandballoon,

Thanks for reporting this issue. We're now aware of it and are tracking this and other ordering issues in a new issue [here](https://github.com/learn-co-curriculum/this-is-react-readme/issues/3). 

We are currently updating and restructuring the materials in this section and will add this to our internal work queue.  We'll be updating the order of lessons in the next phase of this process and will take this information into consideration in upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
